### ISSUE TITLE
api-minimum-version-number should be the major version number

### ISSUE THREAD

**Issue by herrreiprich** [PlugSurfing/oioi-documentation#75]
The example response "minimum-version": "3.3.3" is not sufficient in the documentation. In case api version is not backwards compatible, major version number should change. Example response should be e.g. "minimum-version": "5".

From the client side, you should know what to expect and how to compare version numbers.

Documentation should mention as well that default is "null" in case there is no minimum-version-number set.

**Comment by schemar** [comment]
The thing is that the version numbers are following semantic versioning 2.0.0. According to that, the major number changes for a backwards-incompatible change. Adding a new optional field, for example, would not increase the major number. At the same time, it could be highly desired for mobile applications to include that change. Mobile apps are not the only consumers of the API and we should not frequently increase the major number. What do you think?

**Comment by herrreiprich** [comment]
True, major version number should not increase frequently. I did not understand this call as to be adjusted frequently. Only in the rare case that there is a incompatible change.

For client side integration I see the following problem: Where do I find the current API version that we are actually using? Should I compare just "4.0.0" with "minimum-version-number" response? In case minimum-version-number returns "4.3.1" comparison is false or should I focus on major version number only and use "4" for comparison?

**Comment by schemar** [comment]
The client will need to set this to the version number the client implemented. That info is provided in `docs/conf.py`. Unfortunately "readthedocs" removes the semantic versioning and instead displays "latest", "stable", etc. I will see if I can find a better way to communicate the current version number.

**Comment by schemar** [comment]
I added the full release number to the index page of the documentation.
